#!/bin/zsh
if test `id -u` != "0"; then
  echo "This must be run as root"
  exit 1
fi

if command which -s pfctl; then
	cp ./pf.conf /etc/tt404pf.conf
	launchctl load -w pf.plist
  echo "PF configuration installed"
else
  echo "PF not installed"
  if command which -s ipfw; then
    launchctl load -w ipfw.plist
    echo "ipfw configuration installed"
  else
    echo "ipfw not installed"
    echo "No supported firewalls found. Aborting."
  fi
fi
